DLR-SC/tigl

TIGLViewer/src/TIGLViewerDocument.cpp
Not sure if setting the char length to a constant 90 is adviseable, but my C++ skills have suffert from a couple of years of python. :)
=> Fixed bug in TiGLViewer when loading a cpacs file with multiple models.

src/fuselage/CCPACSFuselageProfile.cpp, src/geometry/CTiglSymetricSplineBuilder.cpp, src/geometry/CTiglSymetricSplineBuilder.h, tests/main.cpp, tests/tiglBSplines.cpp
This fix makes sure, that half profiles are perpendicular to the x-z plane and are thus symmetric. This allows a correct creation of the guide curves.
A new interpolation algorithm had to be implemented that forces symmetric B-Splines.
Please check, if the bug is really closed.
=> Fixed guide curves not in x-z plane (bug 125)

src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/geometry/CTiglMakeLoft.cpp, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CTiglWingBuilder.cpp, src/wing/CTiglWingBuilder.h
To prevent the opencascade fusing problems related to the trailing edge, the TE is now modeled using a ruled ThruSection algorithm instead of coons patches.
I moved the modeling code into the CTiglWingBuilder class. By setting the preprocessor flag NO_EXPLICIT_TE_MODELING, the old behaviour is restored.
=> Explicit modeling of the trailing edge to prevent fuse errors

src/cpacs_other/CCPACSExternalObject.cpp, src/cpacs_other/CCPACSExternalObjects.cpp, tests/TestData/external_component.xml, tests/TestData/simpletest-nacelle.xml, tests/tiglExternalComponent.cpp
Changed the element and attribute names of the external components to be CPACS 2.3 conform.
=> CPACS 2.3 conform external components

CMakeLists.txt, TIGLViewer/CMakeLists.txt, TIGLViewer/src/main.cpp, cmake/FindOpenCASCADE.cmake
Newer OpenCASCADE version (>=6.9.0) require shaders for visualization.
These commits copy the shader files into the TiGL install path. Also, TiGL Viewer check this shader path on startup. If the shaders are not found, an error message is displayed.
=> Integrated OCCT shaders into TiGL

src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingComponentSegment.h, tests/TestData/compseg-rotated.xml, tests/tiglCommonFunctions.cpp, tests/tiglWingComponentSegment.cpp
The full description of the bug can be read in #206.
With the current component segment definition, the coordinate system can be larger than the actual wing plan form. This PR adds the extended outer and inner segment chord faces. Now we can check, whether a point lies on the extended chords or is completely outside of the wing.
=> Fixed an issue in tiglWingComponentSegmentComputeEtaIntersection

TIGLViewer/src/TIGLViewerDocument.cpp, src/configuration/CTiglShapeGeomComponentAdaptor.h, src/generated/TixiHelper.cpp, src/math/CTiglOptimizer.cpp, src/math/CTiglOptimizer.h, src/math/ITiglObjectiveFunction.cpp, src/math/ITiglObjectiveFunction.h, src/system/CScopedLock.h, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingComponentSegment.h, src/wing/CCPACSWingRibsDefinition.cpp, src/wing/CCPACSWingSparSegment.cpp, src/wing/CTiglWingChordface.cpp, src/wing/CTiglWingChordface.h, src/wing/CTiglWingStructureReference.cpp, src/wing/CTiglWingStructureReference.h, src/wing/tigletaxsifunctions.cpp, src/wing/tiglwingribhelperfunctions.cpp, tests/tiglWingComponentSegment.cpp
I implemented the new CS math for the method CCPACSWingComponentSegment::InterpolateOnLine.
Also I cleaned up much of the component segment code by removing:
- extended chord faces
- projected leading edge
- duplicate functions
The GetLoft method of the WingComponentSegment returns the Shape now in global coordinates. This has to compensated in WingStructureReference, which typically uses the Wing Shape in local Coordinates.
=> Further implementation of new CS math and cleanup

TIGLViewer/CMakeLists.txt, TIGLViewer/src/TIGLViewerDocument.cpp, TIGLViewer/src/TIGLViewerVTKExportDialog.cpp, TIGLViewer/src/TIGLViewerVTKExportDialog.h, TIGLViewer/src/TIGLViewerVTKExportDialog.ui, bindings/java/src/de/dlr/sc/tigl/TiglNativeInterface.java, src/api/tigl.cpp, src/api/tigl.h, src/exports/CTiglExportVtk.cpp, src/exports/CTiglExportVtk.h, src/geometry/CTiglPolyData.cpp, src/geometry/CTiglTriangularizer.cpp, src/geometry/CTiglTriangularizer.h, tests/tiglExports.cpp
The only option right now is to enable/disable normal vectors.
This is required, as normals and vertices are pairs in the VTK file format. When we have two equal vertices with different normals, two points are inserted into the VTK file. Codes that rely on having each point only once can disable writing the normal vectors now.
Also fixed some minor issues in the VTK export.
Fixes #254 and fixes #255
=> Added function to set VTK specific options

src/api/tigl.cpp, src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, tests/tiglFuselageSegment.cpp
A function for computing fuselage section center is committed.
Fixes issue #260
=> Added API function tiglFuselageGetSectionCenter

src/api/tigl.cpp, src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, tests/tiglFuselageSegment.cpp
The function tiglFuselageGetCrossSectionArea is committed which
computes the area of a fuselage section. A helper function GetArea
which computes the area of a TopoDS_Shape and the test for
tiglFuselageGetCrossSectionArea are committed as well.
Fixes issue #259
=> Added API func. tiglFuselageGetCrossSectionArea

.travis.yml, appveyor.yml, ci/travis/deploy.sh
This PR enables the following:
- CRON based nightly builds
- The windows and macOS nightlies are uploaded to sourceforge
- Releases - defined by a new tag - are uploaded to the github release page
=> Automatically deploy nightlies and release builds

bindings/python_internal/CMakeLists.txt, bindings/python_internal/common.i, src/api/tigl_internal.h, src/common/typename.cpp, src/common/typename.h, src/cpacs_other/CTiglUIDManager.h, src/exports/CTiglExportVtk.h, src/generated/CPACSFuselages.h, src/generated/CPACSWing.h, src/generated/CPACSWings.h
The internal python interface could not access the new member variable of the VTK exporter. Since this is a data member, the functions and datas must be imported using declspec(dllimport).
This required to remove also the (incorrect) exports on inline functions.
=> Fixed Internal Python Interface build

TIGLViewer/src/TIGLViewerContext.cpp
This helps to debug the shader code without recompilation of tigl viewer. We can use this to debug the black aircraft problem on some graphics cards. I also experiences this in a VM on Ubuntu 15.04, but cannot reproduce this issue on any other VM.
=> Allow shaders to be overridden by the user

misc/get_tigl_tixi.sh
The script downloads all required files from a repository. The hmtl sctructure of the repository has changed, which required a change to the script parser.
Also, I added the possibilty to chose between tigl3 and tigl2.
=> Fixed get_tixi_tigl script

CMakeLists.txt
=> supressing deprecation warning of std::tr1 to allow gtest to compile

TIGLViewer/shaders/PhongShading-v6.fs, TIGLViewer/shaders/PhongShading-v7.fs
On some hardware, aType is always zero - which actually
should not be the case. I don't understand why, but for
the single-lighted TiGL, we can use this workaround.
Fixes #333
=> Workaround for black aircraft issue

TIGLViewer/CMakeLists.txt
Whenever I used a downloaded version of TiGL, I could not save JPEG screenshots.
Local builds didn't have this problem. The reason was, that Qt searches the JPEG plugin 
1. In the current working directory
2. In the Qt installation path
Since the Qt installation path is different on the CI server than on my local machine, it could't find the plugin.
This commit fixes the issue by explicitly installing the jpeg plugin with tigl.
Fixes #349
=> Install qjpeg plugin, to be able to make jpeg screenshots

src/geometry/CCPACSGenericSystem.cpp, tests/unittests/tiglACSystems.cpp
The code mistakenly tried to registers the generic AC system twice at the UID manager. This is now fixed.
Fixes #351
=> Fixed opening of files with generic systems

src/geometry/CTiglTransformation.cpp, tests/unittests/TestData/transformation-benchmark.xml, tests/unittests/tiglMath.cpp, tests/unittests/tiglTransformationBenchmark.cpp
Fixed the order of the transformation multiplication operator. This is actually never used (will be used in future), hence the error was not detected before.
We never had a proper test, that checks all different combinations of global and local transformation. To make sure, that all changes w.r.t. to the transformation tree are correct, this test is required.
=> Fixed matrix multiplication and added transformation benchmark

src/generated/CPACSFuselageCutOut.cpp, src/generated/CPACSFuselageCutOut.h, src/generated/CPACSFuselageCutOut_cutoutType.h, src/generated/CPACSRibCrossingBehaviour.h, src/generated/CPACSRotorHub_type.h, src/generated/CPACSSymmetry.h
I found a bug in the generator which occured with the new CPACS 3 schema. This results in a few type renamings, which are probably not optimal, but we can fix this at another time.
=> Updated to new version of cpacs_tigl_gen

src/cpacs_other/CCPACSExternalObject.cpp
This only happened, when the parentUID was not set.
Fixes #360
=> Fixed missing symmetry in external object (step, igs...)

TIGLViewer/src/TIGLViewerDocument.cpp, TIGLViewer/src/TIGLViewerDocument.h, TIGLViewer/src/TIGLViewerWindow.cpp, TIGLViewer/src/TIGLViewerWindow.ui, bindings/java/src/de/dlr/sc/tigl3/CpacsConfiguration.java, bindings/java/src/de/dlr/sc/tigl3/TiglNativeInterface.java, bindings/python_internal/exports.i, src/api/tigl.cpp, src/api/tigl.h, src/exports/CTiglExportCollada.cpp, src/exports/CTiglExportStep.cpp, src/exports/CTiglExportVtk.cpp, src/exports/CTiglExportVtk.h, src/geometry/CNamedShape.cpp, src/geometry/CNamedShape.h, src/geometry/CTiglPolyData.cpp, src/geometry/CTiglPolyData.h, src/geometry/CTiglTriangularizer.cpp, src/geometry/CTiglTriangularizer.h, src/imports/CTiglStepReader.cpp, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingSegment.cpp, src/wing/CTiglWingBuilder.cpp, src/wing/CTiglWingBuilder.h, tests/unittests/TestData/simpletest-nacelle.xml, tests/unittests/tiglExports.cpp, tests/unittests/tiglExternalComponent.cpp, tests/unittests/tiglImport.cpp, tests/unittests/tiglPolydata.cpp
This required a large refactoring. The most important change is, that each face now stores the UID of the component from which it was generated.
This is required in order to figure out, which component is responsible for adding the metadata.
=> Changed VTK exporter API to match CTiglCadExporter Interface

.travis.yml
CCache caches compiled object files. Reusing the files from the cache can significantly improve build types, in particular, if only few things have changed.
This should reduce review times for PRs. We now only need a cache for windows.
=> Speed up linux and mac builds with ccache

.travis.yml, appveyor.yml, cmake/concat_generated.cmake.in, cmake/tiglmacros.cmake, src/CMakeLists.txt
This results in a adequate compilation speedup , roughly:
* 45 min -> 30 min without compiler cache (e.g. in Windows)
* 13 min -> 9 min with compiler cache (Mac, Linux)
=> Improve build speed by concatenating generated source files into one

appveyor.yml
To use the server, I had to take clcache from pip.
I also chose to have a separate cache directory for
each compiler to avoid confusion between different
architectures.
=> Use clcache server

src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/fuselage/CCPACSFuselage.cpp, src/fuselage/CCPACSFuselage.h, src/wing/CTiglWingBuilder.cpp
Here is some preparation for the fuselage stringer geometry code:
* renamed WireGetFirstPoint and WireGetLastPoint
* added GetFirstPoint and GetLastPoint for edge and shape
* added methods to project wires/edges onto the fuselage loft
* added methods to compute intersections of lines described by stringer frame positions with the fuselage loft
=> Fuselage stringer preparation

bindings/python_internal/configuration.i, src/configuration/CTiglShapeGeomComponentAdaptor.h, src/cpacs_other/CCPACSAircraftModel.cpp, src/cpacs_other/CCPACSAircraftModel.h, src/cpacs_other/CCPACSExternalObject.cpp, src/cpacs_other/CCPACSExternalObject.h, src/cpacs_other/CCPACSRotorcraftModel.cpp, src/cpacs_other/CCPACSRotorcraftModel.h, src/cpacs_other/CTiglUIDManager.cpp, src/cpacs_other/CTiglUIDManager.h, src/fuselage/CCPACSFuselage.cpp, src/fuselage/CCPACSFuselage.h, src/fuselage/CCPACSFuselageSegment.cpp, src/fuselage/CCPACSFuselageSegment.h, src/geometry/CCPACSGenericSystem.cpp, src/rotor/CCPACSRotor.cpp, src/rotor/CCPACSRotor.h, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h, src/wing/CTiglWingChordface.cpp
* using RTTI to automatically register geometric components in CTiglUIDManager::RegisterObject
* made no longer publicly needed methods private in CTiglUIDManager
* removed all explicit registration as geometry components
=> Automatic registration of geometric components

appveyor.yml
The Qt version 5.7 was not anymore installed on appveyor
This commit updates TiGL to Qt 5.10
=> Fixed qt path in appveyor

src/fuselage/CCPACSFuselage.cpp, tests/unittests/TestData/fuselage_structure-v3.xml
Fixed wrong interpretation of reference angle in stringer frame positionings and updated fuselage_structure-v3 to match new interpretation. The correct interpretation is angle 0 pointing towards +Z not -Z.
=> fixed wrong interpretation of reference angle

bindings/python_internal/configuration.i, bindings/python_internal/geometry.i, src/fuselage/CCPACSDoorAssemblyPosition.h
The python method CTIglUIDManager::get_geometric_component now returns the correct type dynamically.
=> Implemented downcast of ITiglGeomtricComponent in UIDManager

TIGLViewer/scripts/globaldefs.js, TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerContext.h, bindings/python_internal/configuration.i, examples/python_internal/example_wing_cell_geometry.py, src/wing/CCPACSWingCell.cpp, src/wing/CCPACSWingCell.h, src/wing/CCPACSWingShell.cpp, src/wing/CCPACSWingShell.h, src/wing/CCPACSWingSparSegment.cpp, src/wing/CCPACSWingSparSegment.h, tests/unittests/tiglWingCell.cpp
I integrated the cell geometry from airbus.
The following changes to the original code have been made:
- Adaptations, since CPACSWingCell::m_skin is not optional in our code
- Made the cell a geometric component
- Integrated into the Python wrapper
- Added Python example
@bernhardmgruber , @rmaierl  Can you please commit a description of CCPACSWingShell::SparSegmentsTest? I don't know what this function is for. Is it possible, to extract this method into a separate function?
Closes #448
=>  Integrated cell geometry code from airbus

src/wing/CCPACSWingCell.cpp, src/wing/CCPACSWingCellPositionChordwise.cpp, src/wing/CCPACSWingCellPositionChordwise.h, src/wing/CCPACSWingCellPositionSpanwise.cpp, src/wing/CCPACSWingCellPositionSpanwise.h
Throwing exception in case of unrecognized combination of chordwise and spanwise positionings, this prevents returning uninitialized values
=> Small bug detection

src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineAlgorithms.h, src/geometry/CTiglPointsToBSplineInterpolation.cpp, src/geometry/CTiglPointsToBSplineInterpolation.h, tests/unittests/testctiglbsplinealgorithms.cpp, tests/unittests/tiglBSplines.cpp
This B-spline interpolation is similar to GeomAPI_Interpolate, but has the following features, that the OCCT function does not have:
- Custom Degree
- Symmetric handling of periodic curves
In particular the custom degree is very helpful, since it allows large flexibilty.
Closes #457
=> Implemented custom B-spline interpolation

src/CMakeLists.txt
By using add_library(... OBJECT ...) we can create a target to compile all TiGL sources. This target can then be linked by both, the static and dynamic TiGL library. This avoids compiling TiGL sources twice.
=> Added intermediate object library to avoid compiling TiGL twice

src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/configuration/CTiglShapeGeomComponentAdaptor.h, src/geometry/CNamedShape.cpp, src/geometry/CNamedShape.h, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h
This PR changes existing behavior. GetUpperShape(), GetLowerShape() and GetTrailingEdgeShape() now ignore the TiglShapeModifier (for now), but return shapes taking guide curves into account (which they previously didn't).
=> Implemented GetUpperShape(), GetLowerShape() and GetTrailingEdgeShape() using face traits

src/boolean_operations/CCutShape.cpp, src/boolean_operations/CFuseShapes.cpp, src/boolean_operations/CTrimShape.cpp, src/boolean_operations/GEOMAlgo_Splitter.cxx, src/boolean_operations/GEOMAlgo_Splitter.hxx, src/configuration/CTiglFusePlane.cpp, src/contrib/MakePatches.cxx, tests/unittests/guideCurvePatchesMakeLoops.cpp, tests/unittests/tiglFuseAircraft.cpp
Basically some of the BOP*** classes have been replaced by TopTools. Please have a look if older OCC versions still compile.
=> Allow compiling with OpenCascade 7.3.0

src/geometry/CTiglInterpolateBsplineWire.cpp, tests/unittests/tiglFuselageGetPoint.cpp, tests/unittests/tiglFuselageSegment.cpp
By using now our own interpolation algorithm, the
symmetry of the fuselage section is restored and
the z value gets zero.
Fixes #512
=> Fix non-symmetric B-Spline profiles

src/common/sorting.h, src/fuselage/CCPACSFuselageSegments.cpp, src/fuselage/CCPACSFuselageSegments.h, tests/unittests/testsorting.cpp
When the segments are in wrong order,
a warning is printed and the segments will be ordered.
Fixes #540
=> Fixed unordered fuselage segments

appveyor.yml, cmake/FindPythonOCC.cmake
Builds the swig generated python bindings as part of the windows CI process.
Any errors in the bindings should now become obvious.
=> Build internal bindings on windows ci

src/geometry/CTiglTransformation.cpp, src/geometry/CTiglTransformation.h, tests/unittests/tiglMath.cpp
The matrix decomposition in CTiglTransformation wrongly produced extrinsic xyz Euler angles, rather than intrinsic xy'z'' Euler angles. 
Fixes #590
Includes the Unit test provided by @cfsengineering in the original issue #590
- ~~New classes have been added to the Python interface.~~
- ~~API changes were documented properly in tigl.h.~~
=> Fix wrong matrix decomposition

src/geometry/CTiglTransformation.cpp, src/geometry/CTiglTransformation.h, src/rotor/CCPACSRotor.cpp, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h
Fixed issue #509 
I provided a fix for the rotor transform issue. The main problem is, that it is possible via cpacs to give the rotor blade a parent which is not the rotor. This leads to strange transformation chain, resulting in a wrong placement of the rotor.
My workaround simply remove a potential parent from the blade, if it is a rotor blade.
I tested this with the simplerotors example as well as the attached helicopter in the issue. I played around with and without parent and checked, that all tests are still working.
-  **no new classes** 
-  **no api changes**
=> Fix for rotor transform issue

src/engine_nacelle/CCPACSNacelleCowl.cpp, src/engine_nacelle/CCPACSNacelleProfile.cpp, src/geometry/CCPACSRotationCurve.cpp, src/geometry/CCPACSRotationCurve.h, tests/unittests/TestData/simpletest-simplenacelle.cpacs.xml
This PR fixes a few small issues that came up with the engine nacelle generation, if the CPACS file is not perfectly according to the current standard.
This PR fixes #586 #603 and #605
So far only manually, no tests added to test suite
- ~A test for the new functionality was added.~ *(no new functionality)*
- ~New classes have been added to the Python interface.~ *(no new classes)*
- ~API changes were documented properly in tigl.h.~ *(no new API changes)*
=> Make engine nacelle creation more robust

src/api/tigl.cpp, src/api/tigl.h, src/configuration/CCPACSConfiguration.cpp, src/cpacs_other/CTiglUIDManager.cpp, tests/unittests/tiglWing.cpp
fixes #614
- To calculate the wetted area of the wing, the wing must be cut with the fuselage, which is read as the parent geometric component of the wing. But the parentUID element of the wing is optional, and TiGL used to crash if no parent were to be found.
- Now, the API function tiglGetWettedArea returns the wetted area of the wing if the wing has a parent. Else, it returns the surface area of the wing (API change).
- In addition, a minor bug in line 237 of CTiglUidManager.cpp was fixed.
A unit test has been added that tests the API function for success.
=> bugfix in tiglWingGetWettedArea

TIGLViewer/src/TIGLViewerDocument.cpp, bindings/java/src/de/dlr/sc/tigl3/TiglNativeInterface.java, src/api/tigl.cpp, src/api/tigl.h, src/common/Debugging.cpp, src/common/Debugging.h
Added api function ```tiglSetDebugDataDirectory``` to specifiy the directory of the crashdump data.
Added api function ```tiglSetDebugDataDirectory``` to specifiy the directory of the crashdump data.
TiGL Viewer used the function by setting this directory relative to the currently opened CPACS file.
This was necessary, as installed TiGL Viewer could not write into the current working directory.
* Installed TiGL into system directory.
* Provoked an error. The crashdump was written into the directory relative to the cpacs file.
* If the cpacs file is in a write-protected directory, a warning will be logged. No crash occured.
=> 591 custom crashinfo path

bindings/python_internal/geometry.i, bindings/python_internal/tigl3/curve_factories.py, bindings/python_internal/tigl3/occ_helpers/containers.py, examples/python/example_bspline_intersection.py, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineAlgorithms.h, src/geometry/CTiglBSplineApproxInterp.cpp, src/geometry/CTiglLineSegment.cpp, src/geometry/CTiglLineSegment.h, src/math/CTiglIntersectBSplines.cpp, src/math/CTiglIntersectBSplines.h, src/math/CTiglProjectPointOnCurveAtAngle.cpp, tests/unittests/test.h, tests/unittests/testBSplineIntersection.cpp, tests/unittests/tiglCommonFunctions.cpp
Implemented a 3D intersection algorithm for B-splines.
A hopefully robust 3D intersection algorithm for B-splines was implemented.
The previous implementation basically used OpenCASCADE often lead to wrong or
missing intersection points. A robust algorithm is required for the curve network interpolation
though.
The implementation  divides the input curves and checks, if their bounding boxes (convex hulls)) intersect each other. If so, this process is repeated until the curve segment is almost a line segment. This result is used to locally optimize into a true minimum.
1. Prototypical implementation in SplineLib with many different examples
2. Manual verification of the results
3. Unit test that compares the results with the python results, that turned out to be correct.
4. Another unit …
=> Robust B-Spline Intersection Algorithm

TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerContext.h, TIGLViewer/src/TIGLViewerSettings.cpp, TIGLViewer/src/TIGLViewerSettings.h, TIGLViewer/src/TIGLViewerSettingsDialog.cpp, TIGLViewer/src/TIGLViewerSettingsDialog.ui, TIGLViewer/src/TIGLViewerWindow.cpp
Implemented plotting face boundaries as black lines.
This option can be turned on/off in the settings menu.
=> Added option to draw face boundaries in TiGl Viewer

src/api/tigl.cpp, src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/geometry/CTiglAbstractGeometricComponent.cpp, src/geometry/CTiglAbstractGeometricComponent.h, tests/unittests/testperformance.cpp
This PR adds a bounding box check as a pre-phase to `IsPointInsideShape` to improve the performance of `tiglCheckPointInside`.
This PR fixes #646
A new performance test has been added to the unit tests. For the [`CPACS_30_D150`](https://github.com/DLR-SC/tigl/blob/master/tests/unittests/TestData/CPACS_30_D150.xml) test case, four points are tested against three components, the wing, the VTP and the fuselage. Of the four points, one is exclusively in the wing, one in the VTP, one in the fuselage and one does not lie in any component. 
Thus, for each of the three tested components, three of four points are outside of the bounding box, and one point should result in a return value `true`.
```bash
[ RUN      ] TestPerformance.tiglCheckPointInside
Time tiglCheckPointInside wing [us]: 8380
Time …
```
=> Add bounding box check to `tiglCheckPointInside`

src/boolean_operations/CMergeShapes.cpp, tests/unittests/TestData/symmetry_exportBUG.xml, tests/unittests/tiglExports.cpp
This fixes #647 with a relaxed tolerance in `CMergeShapes`. See the description of the original issue.
A test case and a unit test have been added
- ~~New classes have been added to the Python interface.~~
- ~~API changes were documented properly in tigl.h.~~
=> Fix bug for exporting fused symmetric geometric components

bindings/java/src/de/dlr/sc/tigl3/TiglGeometricComponentIntentFlags.java, bindings/java/src/de/dlr/sc/tigl3/TiglGeometricComponentType.java, bindings/java/src/de/dlr/sc/tigl3/TiglGetPointBehavior.java, bindings/java/src/de/dlr/sc/tigl3/TiglNativeInterface.java, bindings/java/src/de/dlr/sc/tigl3/TiglShapeModifier.java, src/api/tigl.cpp, src/api/tigl.h, tests/unittests/cpacsConfiguration.cpp
Added new api function tiglComponentGetType, which returns the type of a geometric element, given its UID.
The basically adds an api function for a functionality we already have in TiGL.
Why is this necessary? Sometimes you need to know, whether you are on a component segment or e.g. a trailing edge device. This makes it possible.
Closes #663
I created a simple test that checks some of the most common elements.
=> Added new api function tiglComponentGetType

.github/workflows/build-test-deploy.yml, README.md
@rainman110, could you please check if the MacOS artifact works on older distros than 10.15 once the CI runs are through?
fixes #676
=> Remove Miniconda from Linux/MacOS Build Chain in Github CI

.github/workflows/build-test-deploy.yml
This PR modifies the CI in such a way, that a PR is created at tigl-website to integrate the latest documentation at a newly created tag.
Fixes #681 
Tested on master branch with a test-release of a forked repo.
=> Create a PR at tigl-website at new release

.github/workflows/build-test-deploy.yml
=> Don't install ccache from HEAD for MacOS CI

bindings/python_internal/configuration.i
=> add CTiglControlSurfaceTransformation to python bindings

src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/fuselage/CCPACSFrame.cpp, tests/unittests/TestData/bugs/694/test_frame.xml, tests/unittests/tiglCommonFunctions.cpp, tests/unittests/tiglFuselageFrames.cpp
Added fix for geometry generation of fuselage frame defined via 2 positionings, where the first one has a higher reference angle than the second one.
This PR fixes #694
Added testcase TestFuselageFrames.bug694
=> Bugfix for issues in frame geometry generation

cpacs_gen_input/cpacs_schema.xsd, src/TiglSymmetryAxis.h, src/api/tigl.h, src/engine_pylon/CCPACSEnginePylon.cpp, src/generated/CPACSCpacs.h, src/generated/CPACSProfileGeometry2DType_symmetry.h, src/geometry/CCPACSGenericSystem.cpp, src/geometry/CTiglRelativelyPositionedComponent.cpp, src/geometry/CTiglRelativelyPositionedComponent.h, tests/unittests/testSymmetry.cpp
Implemented new symmetry flags "none" and "inherit"
With the current implementation and the CPACS interpretation, it is not possible to remove a symmetry flag from a component, if the parent component has set a symmetry. A current workaround is setting the symmetry flag to an empty string, which is however not CPACS conforming.
This PR makes these implicit behaviour more explicit and adds two new ways to define the symmetry.
- The flag "none" basically deletes the symmetry flag from the parent and disables the symmetry
- The flag "inherit" is, what is the currenty default bahaviour of cpacs. It takes the symmetry from the parent. Omitting a symmetry flag is the same as using inherit. The intention of adding "inherit" is, to make the symmetry more explicit from a symantic point of view. It …
=> Implemented new symmetry flags

src/fuselage/CCPACSPressureBulkheadAssemblyPosition.cpp, tests/unittests/TestData/bugs/710/test_fuselage_walls_ex1.xml, tests/unittests/TestData/test_fuselage_walls_ex1.xml, tests/unittests/TestData/test_fuselage_walls_ex2.xml, tests/unittests/TestData/test_fuselage_walls_ex3_labyrinth.xml, tests/unittests/TestData/test_fuselage_walls_ex4_compartment.xml, tests/unittests/tiglFuselageFrames.cpp
CCPACSBulkheadAssemblyPosition should throw an exception if the reference frame does not have enough frame positions.
In contrast to TiXI 3.0.3, TiXI 3.1.0 checks in `tixiGetDoubleElement` wether the element string is numeric. Unfortunately -until DLR-SC/tixi#161 is merged - it also throws an error for strings that are numeric, but contain trailing whitespaces. This caused the `ReadCPACS` function to fail if the CPACS file contains any trailing whitespaces. With some relevant CPACS nodes missing, the geometry creation of CCPACSBulkheadAssemblyPosition crashed.
In this PR 
- The whitespace is removed from some of the affected test cases, so that TiXI does not crash
- CCPACSBulkheadAssemblyPosition now throws an error instead of crashing, if the number of frame positions in the reference …
=> Fix SegFault in CCPACSBulkheadAssemblyPosition with TiXI 3.1.0

.github/workflows/build-test-deploy.yml
The CI Cache of doxygen and matlab for windows does not work properly: Sometimes an empty directory is cached after the download failed.
Fixes #718
=> Remove thirdparty CI cache

.github/workflows/build-test-deploy.yml
Somehow, the linking command "ar" cannot be found.
Setting the cmake_compiler_launcher should be enough.
No reason to set CC/CXX variables, which seems to cause issues.
=> Try to fix macos building problems

.github/workflows/build-test-deploy.yml, bindings/matlab/common.h
This PR:
- Fixes the failing matlab libs download by using conda packages of the matlab libraries
- Also builds the matlab bindings on macos
=> CI matlab issues

.github/workflows/build-test-deploy.yml
Changes in this PR:
- Since we start the CI builds on push, there is no need to run them on an (internal) PR, so the `on: pull_request` is removed.
- It should be safer to run all CI builds from external forks also for other branches than PRs onto master, so this restriction is changed as well.
Oh and also this PR tests if the builds are started for PRs from external forks at all.
=> run CI on external PRs only, remove branch restriction

bindings/java/CMakeLists.txt, examples/java_demo/CMakeLists.txt, examples/java_demo/build.gradle.in
Improved building of java bindings, if tixi is added as a submodule.
For #736 , I simply removed the version argument for find_package.
For #737, I  am now using generator expressions.
Fixes #737  and fixes #736
=> Fix java tixi local

src/fuselage/CCPACSFuselageProfile.cpp, src/fuselage/CCPACSFuselageProfile.h, tests/unittests/TestData/bugs/747/simpletest_fuselage_guides.cpacs.xml, tests/unittests/tiglFuselageGuideCurves.cpp
Previously, the Lofter crashes in case of fuselage profiles that don't have a start and end-point at the relative circumenference of 0.25 and 0.75 respectively.
This fixes #747 
I added a new unit test.
=> 747 fuselage guidecurve bug

TIGLViewer/src/TIGLScriptEngine.cpp, TIGLViewer/src/TIGLViewerDocument.cpp, bindings/python_internal/geometry.i, src/CMakeLists.txt, src/common/tiglcommonfunctions.h, src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineAlgorithms.h, src/geometry/CTiglConcatSurfaces.cpp, src/geometry/CTiglConcatSurfaces.h, src/geometry/CTiglGordonSurfaceBuilder.cpp, src/geometry/CTiglTransformation.cpp, src/geometry/CTiglTransformation.h, src/guide_curves/CCPACSGuideCurves.cpp, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingSegment.cpp, src/wing/CTiglWingBuilder.cpp, src/wing/CTiglWingBuilder.h, tests/unittests/TestData/simpletest-with-guides.cpacs.xml, tests/unittests/testctiglbsplinealgorithms.cpp, tests/unittests/tiglCommonFunctions.cpp, tests/unittests/tiglTransformation.cpp, tests/unittests/tiglWingGetPoint.cpp
This PR enables to use more than 3 guide curves with TiGL.
Several issues had been addressed:
- Correctly detect upper and lower wing surfaces
- Added algorithm to concate surfaces
- Concat all upper / lower surfaces of a wing segment, that is used for the get point methods and others as well.
TODO: We still need a test example.xml file, that demonstrates the functionality. We might use the FFD or another aircraft.
=> Resolve: Enable to use more than 3 wing guide curves

.github/workflows/build-test-deploy.yml
Also, bump the python version from 3.6 to 3.7 in CI
Fixes #757
=> Fix Windows Conda CI failure

.github/workflows/build-test-deploy.yml
This fixes #750 
Some commands used in our Github actions were deprecated on November 16th, which broke our CI pipeline: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This PR replaces the deprecated commands.
=> Update GitHub actions to env files

src/fuselage/CTiglFuselageSegmentGuidecurveBuilder.cpp, src/guide_curves/CCPACSGuideCurveProfile.cpp, src/guide_curves/CTiglCurveConnector.cpp, src/wing/CTiglWingSegmentGuidecurveBuilder.cpp, tests/unittests/TestData/bugs/766/simple_test_guide_curves.xml, tests/unittests/tiglFuselageGuideCurves.cpp
fixes #766. I did not add an `assert` to CTiglPointToBSpline as mentioned in the issue description, because 
- checking for uniqueness up to floating point precision is not super trivial, especially since the class takes a `Handle(TColgp_HArray1OfPnt)` and not an `std::vector`
- It's not really related to the issue
- The assert would only help in debug mode and uncover a fringe case of misuse.
I added a new unit test dedicated to #766.
- ~~[ ] New classes have been added to the Python interface.~~
- ~~[ ] API changes were documented properly in tigl.h.~~
=> Prevent hard crash with guide curves

.github/workflows/build-test-deploy.yml, tests/unittests/tiglWingSegment.cpp
Fixes #772. This makes sure that the text fixtures for `WingSegmentSimple` get properly set up and torn down. Also, `--gtest_shuffle` is enabled in CI to catch this issue in the future.
=> Fix failing unittests if shuffled

bindings/python_internal/configuration.i, cpacs_gen_input/CustomTypes.txt, src/control_devices/CCPACSTrailingEdgeDevices.cpp, src/control_devices/CCPACSTrailingEdgeDevices.h, src/generated/CPACSControlSurfaces.cpp, src/generated/CPACSControlSurfaces.h, src/generated/CPACSTrailingEdgeDevice.cpp, src/generated/CPACSTrailingEdgeDevice.h, src/generated/CPACSTrailingEdgeDevices.cpp, src/generated/CPACSTrailingEdgeDevices.h, tests/unittests/tiglControlSurfaceDevice.cpp
Fixes #759 
This PR properly exposes `CCPACSTrailingEdgeDevices` to the python bindings.
- `CCPACSTrailingEdgeDevice` is retrievable using the uid manager from python
- `CCPACSTrailingEdgeDevice` is retrievable via CPACS traversal and the new `CCPACSTrailingEdgeDevices` getters.
Tested with the following python code, that previously did not work *(see issue description)*:
```python
from tixi3 import tixi3wrapper
from tigl3 import tigl3wrapper
from tigl3.configuration import CCPACSConfigurationManager_get_instance, CCPACSTrailingEdgeDevice
tixi_handle = tixi3wrapper.Tixi3()
tixi_handle.open("D150_v30.xml")
tigl3 = tigl3wrapper.Tigl3()
tigl3.open(tixi_handle, '')
config = CCPACSConfigurationManager_get_instance().get_configuration(tigl3._handle.value)
uid_mgr = config.get_uidmanager() …
```
=> Properly expose trailing edge devices in python bindings

src/control_devices/CCPACSControlSurfaceBorderTrailingEdge.cpp, src/control_devices/CCPACSControlSurfaceWingCutOut.cpp, tests/unittests/TestData/simpletest-flaps.cpacs.xml, tests/unittests/tiglControlSurfaceDevice.cpp
This PR closes #780, see the issue description for details.
A new unit test has been added.
Screenshots are provided in the issue description #780
=> ControlDevices: Support referencing eta-xsi-coordinates relative to a segment

src/fuselage/CCPACSFuselage.cpp, src/fuselage/CCPACSFuselage.h, src/fuselage/CTiglFuselageSegmentGuidecurveBuilder.cpp, src/guide_curves/CCPACSGuideCurve.cpp, src/guide_curves/CCPACSGuideCurve.h, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingSegment.cpp, src/wing/CTiglWingSegmentGuidecurveBuilder.cpp
Before, the guide curve fromCircumeferenceValue was set
by TiGL after connecting the guide curves. If a curve had set
fromGuideCurveUID, both values were written to XML, which
is not allowed.
Now, I added the method CCPACSGuideCurve::GetFromRelativeCircumference
such that an external code can ask for the circumference value, even
if fromGuideCurveUID is set. This was suggested by Roland.
There are many benefits by this approach:
- More functional approach with less side effects
- Fixed invalid xml
- Simpler use of the guide curve. Simplifies calling code
- Better code design that adheres better
to the single responsibilty principle
Closes #665
I ran unit tests and loaded the guide curve example in TiGL Viewer.
=> Fixed invalid cpacs after write

src/fuselage/CTiglFuselageSegmentGuidecurveBuilder.cpp
Fixes #793
Fixes a small bug introduced in https://github.com/DLR-SC/tigl/commit/2164b67f8fe7857f179c111caf6e804dbdc836d9 where I check for the first and last element of a vector that is allowed to be empty.
=> hotfix for #767

src/wing/CCPACSWingSegment.cpp, tests/integrationtests/TestData/bugs/802/802.xml, tests/integrationtests/testBug802.cpp
Fixed OpenCASCADE crash in wingGetPoint on linear loft. The crash was caused, as OpenCASCADE did not allow to create zero-size line segments.
The fix now uses a simple linear interpolation instead.
Note: this does not fix the problem with the wrong face ordering. I added another follow-up issue #803, which is still open.
Fixes #802 
I added an integration test.
=> Fix issue 802 (getPoint on wing linear loft)

.github/workflows/build-test-deploy.yml, TIGLViewer/CMakeLists.txt, cmake/UseOpenCASCADE.cmake
This updated OCE 0.17 to OCCT 7.4.0 for continous integration. All platforms compile fine and use our OCCT 7.4.0 patched binaries.
Unit tests and manuel TiGL Viewer tests.
=> Use OCCT 7.4.0 for ci

TIGLViewer/scripts/globaldefs.js, TIGLViewer/src/TIGLScriptProxy.cpp, TIGLViewer/src/TIGLScriptProxy.h, src/api/tigl.cpp, src/geometry/CTiglTriangularizer.cpp, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h, tests/unittests/tiglWingSegment.cpp
I had to change the class structure / method signature slightly
to allow to pass, how GetEtaXsi is evaluated.
Unfortunately, GetEtaXsi on the paramter surfaces is almost
a factor of thousand slower, which could be a problem for the
VTK export with metadata. Therefore I decided to use the old
eta / xsi interpretation for the exports for now.
closes #808
To validate, I changed the consistency test, added a performance
test and added a function to tiglviewer to play around with
the function.
=> Respect PointBehaviour for tiglWingGetSegmentEtaXsi

cpacs_gen_input/cpacs_schema.xsd, src/CCPACSPoint.cpp, src/CCPACSPoint.h, src/control_devices/CCPACSControlSurfaceBorderTrailingEdge.cpp, src/control_devices/CCPACSTrailingEdgeDevice.cpp, src/control_devices/CControlSurfaceBorderBuilder.cpp, src/control_devices/CControlSurfaceBorderBuilder.h, src/generated/CPACSControlSurfaceHingePoint.cpp, src/generated/CPACSControlSurfaceHingePoint.h, src/generated/CPACSControlSurfacePath.cpp, src/generated/CPACSPoint.cpp, src/generated/CPACSPoint.h, tests/unittests/TestData/canards.xml
To support canard style flaps, the following changes had to be implemented:
- Create wing cutouts / flap pofiles that can include also the leading edge of the wing
- To allow placing the hinge points outside the wing, I implemented an absolute translation. This required an extension of the cpacs schema, which now includes an optional "translation" node for hinge points
Closes #816 
I tested different settings with TiGL Viewer. The canard flap can now be either some part of the wing or the whole wing at once.
=> Added support for canard style flaps

bindings/python_internal/tigl3/surface_factories.py
After the update to OpenCascade 7.4 the TiGL Curve factories did not work anymore. The problem was, that a python list of swig wrapped `Geom_Curve` instances could not be converted to a `std::vector` of `Handle(Geom_Curve)` automatically. This is now done using the helper function `tigl3.occ_helpers.containers.geomcurve_vector`
Fixes #823.
The following code, taken from this [TiGL example](https://github.com/rainman110/tigl-workshop/blob/master/Exercises/solutions/Exercise3_Geometry-solution.ipynb) fails without the fix:
<details>
<summary>Click to expand Python Code</summary>
```python
import tigl3.curve_factories
import tigl3.surface_factories
from tigl3.geometry import CurveList, BSplineCurveList
from OCC.Core.gp import gp_Pnt
from OCC.Display.SimpleGui import init_display
import numpy …
```
=> fix surface factories curve list arguments

src/common/tiglcommonfunctions.cpp
Previously, a zero-length wire would throw an exception in WireGetPointTangent. With this change, it doesnt, but a singular tangent is returned.
Addresses #819
No new tests were added for this refactor. All existing tests still work.
=> allow zero-length wires in WireGetPointTangent

.github/workflows/build-test-deploy.yml
Fixes #845
The CI failed to create cmake packages, as chocolateys "cpack.exe" was used instead of cmakes executable.
This should fix this by providing the full path to cpack.
=> Fix cpack path

src/Version.h, src/api/tigl.cpp, tests/unittests/TestData/testversion_good.xml, tests/unittests/TestData/testversion_no_cpacs_version.xml, tests/unittests/TestData/testversion_too_old.xml, tests/unittests/testCpacsVersion.cpp, tests/unittests/testVersion.cpp
Fixed parsing the cpacs version.
Previously, the cpacs version could not be parsed correctly, if a patch level version was included in the version string.
This PR adds proper semantic versioning. A new class for parsing semantic versions based on std::regex has been added. Tests have been added accordingly.
Fixes #830 
I added tests for the new semantic versioning class and tests that check opening the cpacs files with correct and incorrect cpacs versions.
=> Fixed parsing of CPACS versions

src/wing/CCPACSWing.cpp, tests/unittests/tiglWing.cpp
The wing invalidation logic contained a reset, which is simply wrong. Invalidation should only affect cached values and not change any other values. Removing Reset fixes the bug.
Fixes #849 
I added a unit test that should check this in future.
=> Fix strange invalidation side effect for wings

ChangeLog.md, src/api/tigl.h, src/geometry/CTiglAbstractGeometricComponent.cpp, src/geometry/CTiglAbstractGeometricComponent.h, src/math/tiglmathfunctions.cpp, src/math/tiglmathfunctions.h, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h, src/wing/TiglWingHelperFunctions.cpp, src/wing/TiglWingHelperFunctions.h, tests/unittests/tiglWing.cpp
The computation of  the aspect ratio need to project the wing to a planform . The plane to be projected is typically the x-y plane. In cpacs however, users have the freedom to build the aircraft in another (rotated) way, so using the x-y plane is too restrictive.
The bug occured, because a wrong projection plane was selected. This led to a very small wing surface area and hence a large aspect ratio. 
This code change fixes the issue by improving the selection of the projection plane. The code was back-ported from CPACS Creator, were the issue was already fixed before.
Closes #827 
A system test was added checking roughly the correct AR value.
=> Fixed incorrect computation of wing aspect ratio

ChangeLog.md, TIGLViewer/src/TIGLViewerDocument.cpp, TIGLViewer/src/TIGLViewerDocument.h, src/api/tigl.cpp, src/exports/CTiglCADExporter.cpp, src/exports/CTiglCADExporter.h, tests/unittests/tiglExports.cpp
This improves the robustness of the non-fused CAD export. It will export as much as possible, even if
one component failed to built. In this case, the user still gets an exported file but an error code is returned.
- I catch all geometry building problems.
- If an error occurs, this is remembered and returned as an error.
- Minor refactoring of error messages, if a TiGL error occurs in TiGL Viewer.
I tested it with some CPACS files, where e.g. the pylons fail to create (because there are invalid).
=> Improved robustness of CAD export

bindings/python_internal/CMakeLists.txt
This PR improves the linking with the python libaries by using the Python3 cmake module. 
The previous approach tried to deduce compile flags, which seemed to be failing on conda with python 3.9 because the flags included the compiler executable as well.
Closes #855
The tigl3 conda package already contains these changes in form of a patch and fixes the conda package build, see https://github.com/DLR-SC/tigl-conda/runs/4251771877?check_suite_focus=true.
=> Try to modernize python linking

.github/workflows/build-test-deploy.yml
The CI problems on windows are fixed by disabling clcache. Clcache was used to speed up compilation but somehow now fails compiling the dummy.cpp file.
I tried putting some code into dummy.cpp without success.
Since most of the time, the clcache cache was empty and we have parallel builds, disabling clcache won't really change build times.
=> Fix windows CI

.github/workflows/build-test-deploy.yml
Github Actions just updated their macOS latest image to 11.6, which now breaks the deployment stage.
This build fixes the macOS by reverting to the macOS 10.15 image used before.
=> Fix macOS CI

bindings/python_internal/configuration.i, src/engine_nacelle/CCPACSEnginePosition.h
fixes #858
This adds the CCPACSEnginePosition to the swig exports. 
Tested with a local conda build.
=> add CCPACSEnginePosition to swig interface

.github/workflows/build-test-deploy.yml
Currently all builds fail on GH hosted windows-2022 runner. We should investigate this later and switch to windows-2019 for now.
=> CI: windows-latest  to windows-2019

misc/get_tigl_tixi.sh
Fixes #884. We needed to fix the tixi minor version to the one available in the opensuse repo: https://download.opensuse.org/repositories/science:/dlr/xUbuntu_18.04/
=> Update get_tixi_tigl.sh Script

src/exports/CTiglCADExporter.cpp
Fixes #897. See description in issue.
existing unit and integration tests
=> Don't export fuselage and wings segmentwise.

TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerDocument.cpp, TIGLViewer/styles/qdarkstyle/README.md
Fix typos in TIGLViewer  
Found via `codespell -q 3 -S thirdparty -L ane,ans,childs,globaly,inout,ist,oce,ontop,parm,parms,te`
n/a
n/a
=> Fix typos in TIGLViewer

TIGLViewer/src/TIGLViewerApp.cpp, TIGLViewer/src/TIGLViewerApp.h, TIGLViewer/src/TIGLViewerWidget.cpp, src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineAlgorithms.h, src/geometry/CTiglBSplineApproxInterp.cpp, src/geometry/CTiglBSplineApproxInterp.h, src/geometry/CTiglInterpolatePointsWithKinks.cpp, src/structural_elements/CCPACSFuselageWallSegment.h, src/wing/CCPACSWing.cpp, tests/integrationtests/TestData/D150WithGuides.xml, tests/integrationtests/testShapeInvalidation.cpp, tests/integrationtests/tiglFuseAircraft.cpp, tests/unittests/testctiglcurvestosurface.cpp, tests/unittests/tiglBSplines.cpp
Leftover typos that alter source code directly. There are also some source comment fixes mixed in.
n/a
=> Fix source code typos

src/wing/CCPACSWingCell.cpp, tests/integrationtests/TestData/bugs/930/IEA-25-310-UWT_ModGrid_final_red_mass_ver_2_loads_CPACS_cc_surface.xml, tests/integrationtests/testBug930.cpp
This PR fixes #930. 
The code for creating wing cells based on contour coordinates contained a small bug in mapping `u` parameters of the wing faces to CPACS contour coordinates: 
The internal `u` parameters go from lower trailing edge over the leading edge to upper trailing edge. The CPACS contour coordinates always go from leading edge to trailing edge. The differentiation between upper and lower side is clear from the CPACS hierarchy. 
This means that for the lower side, the contour coordinates and internal `u` coordinates have a reversed orientation, while for the upper side they do not. This was not properly taken into account before.
A new test case has been added specifically for this issue.
See the issue description #930.
- ~~[ ] New classes have been added to the Python …
=> Fix bug in wing cell creation

src/fuselage/ITiGLFuselageDuctStructure.cpp
I checked out the current master and simply tried.
```
mkdir build
cmake ..
make
```
which leads to the following error:
```
/<user>/git/tigl/src/fuselage/ITiGLFuselageDuctStructure.cpp: In function ‘TopoDS_Wire tigl::{anonymous}::project(TopoDS_Shape, BRepProj_Projection&, tigl::DebugScope&)’:
/<user>/git/tigl/src/fuselage/ITiGLFuselageDuctStructure.cpp:111:60: error: variable ‘TopTools_ListIteratorOfListOfShape it’ has initializer but incomplete type
111 |         for (TopTools_ListIteratorOfListOfShape it(wireList); it.More(); it.Next()) {
|                                                            ^
/home/kisle/git/tigl/src/fuselage/ITiGLFuselageDuctStructure.cpp:128:60: error: variable ‘TopTools_ListIteratorOfListOfShape it’ has initializer but incomplete type
128 |         for …
```
=> Fix unable to compile TiglViewer on  gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

cmake/createDoc.cmake, doc/Doxyfile.in
Inlcuded option to not build pdf documentation.
Configured doxygen to parse all headers
fixes #943
=> provide a list of all cpp functions and classes  in documentation

TIGLViewer/src/TIGLQAspectWindow.cpp, TIGLViewer/src/TIGLViewerWidget.cpp, TIGLViewer/src/TIGLViewerWidget.h, TIGLViewer/src/main.cpp
This is a backport from out GTlab code and also works well for TiGL.
Please test this by setting the screen scaling (under windows display settings) to 200%.
This includes:
- Proper view scaling
- Conversion between relative mouse coordinates and opengl mouse interactions
- Fixup for the rubber band geometry
Closes #953
I tested it by either setting the windows scaling settings and by settings the variable QT_SCALE_FACTOR to a larger value than 1.0.
Before:
After:
=> Implemented high dpi screen support

src/wing/CCPACSWingSegment.cpp, tests/unittests/tiglWingSegment.cpp
The API function tiglWingGetSegmentUpperSurfaceAreaTrimmed(...) terminated with return code 1, when passing the valid arguments (tiglHandle, 1, 1, 0, 0, 0, 1, 0.05, 1, 0.05, 0, double*ReturnValue).
This bug arises due to the fact that the implementation of the mentioned function contained a cast from TopoDS_Compound to a TopoDS_Face. As the used test data configuration has the property, that both its upper and lower wing consists of more than one face, respectively, arising through the use of additional guide curves, both the upper and lower wing are given by compounds containing more than one element, respectively. Trying to cast each of these compounds to a face yields an error.
The bug originates due to the fact that earlier, both upper and lower wings consisted of only one face, …
=> Fix tigl wing get segment upper surface area trimmed

CMakeLists.txt, cmake/Findgmsh.cmake, src/CMakeLists.txt, src/mesher/Mesher.cpp, src/mesher/Mesher.h, tests/unittests/tiglMesher.cpp
=> Gmsh integration

TIGLViewer/shaders/PhongShading-v6.fs, TIGLViewer/shaders/PhongShading-v7.fs
This improves the visual quality of the zebra stripe plot in case of low triangulation resolution.
Before, the stripes were computed based on the normal vector of the vertex, not on the fragment. This lead to
visual distortions. Now, we use the normal vector from the fragment shader as offered by the occt api.
See screenshots
Before:
After fix:
=> Improved visual quality of zebra stripes

src/wing/CTiglWingSegmentGuidecurveBuilder.cpp, tests/unittests/tiglWingGuideCurves.cpp
Now the rX-Direction respects the wing coorddinate system
Visual confirmation in TiGL Viewer and new unit test
=> Fix #975: Transform rX-Direction of guide curve with wing coordinate system

TIGLViewer/src/TIGLViewer.h, TIGLViewer/src/TIGLViewerInternal.h, TIGLViewer/src/TIGLViewerWidget.h, TIGLViewer/src/TIGLViewerWindow.cpp, TIGLViewer/src/TIGLViewerWindow.h, src/configuration/CCPACSConfiguration.cpp
This PR is not onto the main branch, but adds changes to the PR #971. These changes were necessary for me to build TiGL locally using OCCT 7.6.2, see https://github.com/DLR-SC/tigl/pull/971#issuecomment-1853777825
=> some changes for compatibility with OCCT 7.6.2

.github/actions/build-macos/action.yml, .github/actions/test-macos/action.yml, .github/workflows/continuous-integration.yml
Closes #977 
Previously, `TiGL-unittests` was not executable in the macos-test job. The reason seems to be that the `tar` archive of the `build` directory was corrupted. Switching from `tar` to `gtar` (GNU tar) works around this issue.
See https://github.com/actions/runner-images/pull/2163 and https://github.com/orgs/community/discussions/24994.
CI works again
Not applicable
- ~~[ ] A test for the new functionality was added.~~
- ~~[ ] The new code complies with the TiGL style guide.~~
- ~~[ ] New classes have been added to the Python interface.~~
- ~~[ ] API changes were documented properly in tigl.h.~~
=> CI: MacOS tests failed due to bizarre tar issue with github actions

src/guide_curves/CCPACSGuideCurves.cpp, tests/unittests/tiglWingGuideCurves.cpp
Fixes #962
This PR adds an internal check if an `std::vector` is empty before trying to access elements. As a consequence, the wing loft and segment loft will be build just as if there were no guide curves defined. 
Note that CPACS 3.3 requires the `guideCurves` node to be nonempty. We are less restrictive here.
A new test has been added
Not applicable
- ~~[ ] New classes have been added to the Python interface.~~ Not applicable
- ~~[ ] API changes were documented properly in tigl.h.~~ Not applicable
=> Fix for hard crash if guiceCurves node is present but empty in wing segment

TIGLViewer/shaders/PhongShading-v7.6.fs, TIGLViewer/shaders/PhongShading-v7.6.vs, TIGLViewer/src/ISession_Text.cpp, TIGLViewer/src/TIGLAISTriangulation.cpp, TIGLViewer/src/TIGLQAspectWindow.cpp, TIGLViewer/src/TIGLQAspectWindow.h, TIGLViewer/src/TIGLViewer.h, TIGLViewer/src/TIGLViewer.qrc, TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerDocument.cpp, TIGLViewer/src/TIGLViewerInternal.h, TIGLViewer/src/TIGLViewerWidget.h, TIGLViewer/src/TIGLViewerWindow.cpp, TIGLViewer/src/TIGLViewerWindow.h, cmake/UseOpenCASCADE.cmake, src/boolean_operations/GEOMAlgo_Splitter.cxx, src/boolean_operations/GEOMAlgo_Splitter.hxx, src/common/tiglcommonfunctions.cpp, src/configuration/CCPACSConfiguration.cpp, src/control_devices/CControlSurfaceBorderBuilder.cpp, src/geometry/CTiglTriangularizer.cpp, src/wing/CCPACSWingSegment.cpp, tests/integrationtests/testWingCellSpar.cpp, tests/unittests/tiglShapeCache.cpp
OpenCASCADE 7.6.2 support
I adapted the code to allow TiGL to be used with OCCT 7.6.1 as well.
Fixes #973
I compiled it with OCCT 7.6.1, executed the unit tests, and started TiGL Viewer.
Here are some notes:
- The colors in TiGL Viewer are somewhat (slightly) different due to the new Color Space in OCCT
- The test WingSegmentGuideCurves.tiglWingGetSegmentUpperSurfaceAreaTrimmed is failing due to some tolerance error. I did not look into it further.
=> Added support for OCCT 7.6.2

src/geometry/CTiglTransformation.cpp, tests/unittests/tiglMath.cpp
Fix issue  #870: Wrong if clause condition caused misinterpretation of the sign and caused wrong rotation in decompose routine
=> Fix bug causing wrong rotor rotation in y direction (fixes #870)

TIGLViewer/src/TIGLViewerDocument.cpp, src/rotor/CCPACSRotor.cpp, src/rotor/CCPACSRotor.h, src/rotor/CTiglAttachedRotorBlade.cpp
Fix the issue of (possible) uninitialized dereference if the CPACS rotor parameter `nominalRotationsPerMinute` is not defined.
A wrapper function is added around `CPACSRotor::GetNominalRotationsPerMinute()` that returns a `0.` if the value is not defined to avoid uninitialized dereference.
Fixes #998
=> Resolve uninitialized dereference in rotor code

TIGLViewer/src/TIGLQAspectWindow.cpp, TIGLViewer/src/TIGLQAspectWindow.h, cmake/UseOpenCASCADE.cmake
The number of features linked into TiGL was reduced in CMake to only selected used features.
A minor change in TIGLQAspectWindow to allow building with OpenCASCADE 7.5
Not
None
=> CMake adjustments for building with OpenCascade 7.5

cmake/UseOpenCASCADE.cmake
In PR #1017, OCC libraries are removed within the CMake configuration even if they are not set. This behaviour results in a hard CMake error in such a case. This PR puts the `REMOVE_ITEM` commands in an `if` condition and checks the existence at first.
Fix issue #1018
=> Add existence check in CMake before removing OCC libs

cpacs_gen_input/cpacs_schema.xsd, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/fuselage/CCPACSFuselageProfileGetPointAlgo.cpp, src/fuselage/CCPACSFuselageProfileGetPointAlgo.h, src/fuselage/CCPACSFuselageSegments.cpp, src/fuselage/CTiglFuselageSegmentGuidecurveBuilder.cpp, src/generated/CPACSGuideCurve.cpp, src/generated/CPACSGuideCurve.h, src/guide_curves/CCPACSGuideCurve.cpp, src/guide_curves/CCPACSGuideCurve.h, src/guide_curves/CCPACSGuideCurveAlgo.h, src/guide_curves/CCPACSGuideCurves.cpp, src/logging/CTiglLogging.cpp, src/logging/CTiglLogging.h, src/wing/CCPACSWing.cpp, src/wing/CCPACSWingProfileGetPointAlgo.cpp, src/wing/CCPACSWingProfileGetPointAlgo.h, src/wing/CCPACSWingSegment.cpp, src/wing/CTiglWingSegmentGuidecurveBuilder.cpp, tests/common/testUtils.h, tests/unittests/TestData/kinks_withGC_ParameterDef.xml, tests/unittests/TestData/simple_test_guide_curves_wrong_gc_Def.xml, tests/unittests/testUtils.cpp, tests/unittests/tiglCommonFunctions.cpp, tests/unittests/tiglFuselage.cpp, tests/unittests/tiglFuselageGuideCurves.cpp, tests/unittests/tiglWingGuideCurves.cpp
Currently, the definition of (starting and end points of) fuselage guide curves is not consistent to user-defined parameterization for (e.g.) kinks. Those guide curve points are, up to now, defined based on the arc length of the start profile and end profile, respectively. While the user-defined parameterization can arbitrary differ from that (see issue #745).
This PR introduces the new CPACS nodes `fromParameter` and `toParameter` to account for this 'problem' to make it easier for users to sync guide curves with kinks.
The node is implemented via a `choice` element and the old implementation is kept as the default case to not get in the way with existing code, CPACS files and tests.
Since the CPACS scheme is changed, it has to be thought about a CPACS PR, as well.
TODO: 
Fix issue #745
=> Consistent implementation for combining fuselage guide curves and kinks   

src/wing/CCPACSWing.cpp, tests/unittests/tiglWing.cpp
See Issue #1022. 
Changed CCPACSWing::GetLoftWithCutOuts() to return a warning and a clean shape if no control surfaces are defined.
Added Unittest to tiglWing.cpp to assert that warning is thrown and shape is valid.
=> fix GetLoftWithCutOuts() in CCPACSWing crashes without warning (Issue #1022) 

bindings/python_internal/configuration.i, src/structural_elements/CCPACSFuselageWallSegment.h, src/structural_elements/CCPACSWalls.h
CCPACSWalls couldn't be processed correctly via swig, due to missing include statements in configuration.i.
Adding those includes fixes the issue.
All required includes in configuration.i were added, which are:
- The header files of the C++ classes that need to be included
- all header files of classes, that deal with types of "boost-optional" or objects related to "ITiglGeometricComponent" that swig can't process otherwise
The changes fixes #1012 and fixes #986.
Running a python script opening the configuration according to Issue  #1012 works as expected, also the geometry is exported successful.
=>  Fix Python wrapper returns SwigPyObject instead of CPACSWalls (Issue #1012) 

.github/pull_request_template.md
I updated the checklist in the PR template
We want to be more disciplined in actually checking the template. In many PRs, the tasks in the checklist are meaningless, which means in many PRs they are never checked and simply ignored. I think this causes us as contributors and reviewers to be a bit lax. I updated it so that both contributors and reviewers must add a check in each row.
=> Update Checklist in PR template

bindings/python_internal/configuration.i, src/fuselage/CCPACSFuselage.cpp, src/structural_elements/CCPACSFuselageWallSegment.h, src/structural_elements/CCPACSWalls.h, src/wing/CCPACSWing.cpp, tests/unittests/creatorFuselage.cpp, tests/unittests/creatorWing.cpp
Currently, in the CPACS-Creator a section can be added within or next to a segment that contains guide curves (issue #626).
Right now, this results in an error occuring elsewhere or undefined behaviour. Therefore, for the moment it should not be allowed for a user to do this.
From a CPACS perspective it seems reasonable: The guide curves are generally defined after all sections are created as the guide curves depent on them.
Fixes #626 
If users seek for this feature, we can think about a way to handle this. But it should not be an urgent task.
=> CPACS-Creator: Add error handling when a section should be added in (or next to) a segment containing guide curves

CMakeLists.txt, ChangeLog.md, src/CMakeLists.txt
This PR updates the C++ standard to 17 to make use of newer coding features.
Moreover, the standard was also defined in the `src/CMakeLists.txt` which seems redundant. Now, the C++ standard only needs to be defined in the `<ROOT>/CMakeLists.txt`.
| At least one test for the new functionality was added.  | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [x] OK</li></ul> |
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [x] does not …
=> Update to C++17 standard

ChangeLog.md, bindings/python_internal/configuration.i, src/CCPACSPositionings.cpp, src/CCPACSPositionings.h, tests/unittests/tiglWingSegment.cpp
Added Getter functions to CCPACSPositionings.h to make Positionings available via Python Bindings, which is currently not true for classes that store elements using the std::vector<std::unique_prt<**TYPE**>> and don't provide getter functions that return elements by index.
For further information see  https://github.com/RISCSoftware/cpacs_tigl_gen/issues/59
New Functions:
CCPACSPositionings::GetPositioningCount()
CCPACSPositionings::GetPositioning(int index)
Implements Getter functions manually, as discussed in https://github.com/RISCSoftware/cpacs_tigl_gen/issues/59, to fix missing functionality as described in #936.
Functions returning the type std::vector<std::unique_prt<**TYPE**>> will still not be available via Python Bindings.
Added a test, checking missing functionality described …
=> Added Getter functions to CCPACSPositionings.h 

src/wing/CTiglWingSegmentList.h
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| The code is properly documented with doxygen docstrings | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Changes are documented at the top of ChangeLog.md …
=> Add missing include guard

ChangeLog.md, src/geometry/CCSTCurveBuilder.cpp, src/geometry/CCSTCurveBuilder.h, tests/unittests/tiglWingCSTProfile.cpp
Fixes #1048 
This PR adds the option to set the algorithm in CCSTCurveBuilder. The current algorithm based on a Chebychev approximation creates relatively good curves with few control points, but it potentially introduces discontinuities in the curvature, because the approximation is performed segmentwise and the segments are concatenated without taking second derivatives into account. 
With the changes introduced here, the CCSTCurveBuilder constructor gets a new optional enum argument, to switch the algorithm to OCCT's GeomAPI_PointsToBSpline implementation for the approximation. This results in a C3 continuous B-Spline of degree 4 which is much smoother, but may have more control points.
The existing CSTApprox tests have been parametrized, such that the both algorithms are tested. In …
=> Add GeomAPI_PointsToBSpline as an optional alternative algorithm in CSTCurveBuilder

.github/workflows/continuous-integration.yml, cmake/CodeCoverage.cmake
This PR basically just makes sure that the coverage reports are generated on Ubuntu 22.04 instead of Ubuntu 24.04. I do not fully understand why we started receiving lcov errors after `ubuntu-latest` became `ubuntu-24.04`, but for now, this resolves the issue.
Previously, the cmake target for generating coverage reports also generated human-readible html files. These aren't really used by us, because we are directly uploading the lcov *.info files to codecov.org without any further post-processing. Since I wasn't sure if this html generation was causing the problems, I disabled the generation of the html files by default. I added a cmake option so that the html files can still optionally be generated. 
I tested it locally on a Ubuntu 22.04 and managed to reproduce the error in a Ubuntu …
=> Fix CI: Linux Test job capturing code coverage is broken

TIGLViewer/CMakeLists.txt
The title sais it all.
TiGLViewer still builds locally and in CI.
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| The code is properly documented with doxygen docstrings | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [ ] …
=> TIGLViewer: Use GLOB_RECURSE in CMake for src files, no more need for manual addition of .h, .cpp or .ui files

src/api/tigl.cpp
This makes `tiglExportComponent` respect the symmetry option of `tiglSetExportOptions`, e.g.
tiglSetExportOptions("brep", "ApplySymmetries", "true");
such that a symmetric shape is exported if requested.
Before, only the asymmetric shape has been exported, ignoring the symmetry flag.
__Note__: This might break the behavior of client code that assumes non-symmetric geometries, even if the symmetry flag has been set.
Closes #1060
Manually.
| At least one test for the new functionality was added.  | …
=> Make `tiglExportComponent` respect symmetries

TIGLViewer/src/TIGLViewerInternal.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/geometry/CTiglBSplineFit.cpp, src/geometry/CTiglBSplineFit.h, src/geometry/CTiglIntersectionCalculation.cpp, src/imports/CTiglStepReader.cpp, src/math/tiglMatrix.h
These small changes port TiGL to OpenCASCADE 7.8. 
Most changes are cosmetic ones. Only for the hash computation, we cannot use anymore a hash maximum
value, which was probably never a good idea, but it will change the resulting hashes.
This should be no problem, since the hashes are mostly used internally. 
I just compiled and ran TiGL Viewer successfully. 
I hope that the unit test will be successful ... keeping fingers crossed 😏 
| At least one test for the new functionality was added.  | …
=> Ported to OCCT 7.8.x

ChangeLog.md, TIGLViewer/src/TIGLViewerSettings.cpp, src/fuselage/CCPACSFuselageSegments.h
CPACSCreator uses a system-wide config file to store (among many others) the path to the profiles database.
If TiGL is built in a second configuration on the same system, the first build will determine the path in this config file.
If then later the first build (and path) is removed, TiGL will still try to load the database from this path. This PR includes a check, whether the path exists and overwrites the config file entry when it does not.
Fix #1087
Fix #1086 with two missing `TIGL_EXPORT`s
| …
=> Add check for profiles database path within CPACSCreator

.github/workflows/continuous-integration.yml, bindings/python_internal/CMakeLists.txt, environment.yml
This PR introduces several changes
1. Use Python from within conda environment, if exists. Previously, CMake picked up the system-wide Python version on Windows when building the internal python bindings, which caused a conflict.
2. Sometimes the internal python bindings fail to build when using a parallel build, see issue #1103.
3. CI: Remove deprecated windows-2019 runners
4. Bump Qt from 5.15.8 to 5.15.15, because the previous version caused issues with autouic on Windows in CI.
Fixes #1103 
Tested locally on Windows 11 and Ubuntu 22.04 and in CI
None. 
|---------------------------------------------------------|----------------------------- …
=> Small fixes to our build chain

ChangeLog.md, src/fuselage/CCPACSFuselageSegments.cpp, src/wing/CCPACSWingSegments.cpp, tests/unittests/creatorFuselage.cpp, tests/unittests/creatorWing.cpp
When a user adds a non-boundary segment to a wing/fuselage, the respective segment is split and a new one is created. After this split, a reordering of the segments is necessary. Otherwise, the segments cannot be lofted and created correctly. That would result in a wrong visualization and errors when trying to build them on user's demand in the tiglviewer.
For that reason, the `CCPACSFuselageSegments::ReorderSegments()` and CCPACSWingSegments::ReorderSegments(), respectively, were added within the call of the `SplitSegment()` function.
Testing was done by observing the behaviour of the tiglviewer. The root issue for the wrong visualization was that segments were not or wrong displayed in the GUI. Hence, a unittest was added working on the file the behaviour was tested on and fixed.
Here …
=> Reorder segments after the user adds a new segment

ChangeLog.md, TIGLViewer/src/modificators/ModificatorWingWidget.cpp, TIGLViewer/src/modificators/ModificatorWingWidget.ui, TIGLViewer/src/modificators/SymmetryComboBoxWidget.cpp, TIGLViewer/src/modificators/SymmetryComboBoxWidget.h
Fixes #1143
The problem is that changing the symmetry plane of a wing has an influence on the reference area, sweep, dihedral and aspect ratio. When the symmetry axis is changed, the spinboxes for setting the top area, aspect ratio, etc. are not changed, but the values are recalculated internally. From this difference, the ModificatorWingWidget deduces that e.g. the aspect ratio has changed and calls the associated function, actually changing the geometry. For some choices the calculated reference area is nonsensical, e.g. 0. When applying the change, TiGL crashes.
--------------------
Now, before we call ModificatorWingWidget::apply, we connect the combobox of the symmetry with a function that recalculates the reference area, sweep, dihedral and aspect ratio and sets the comboboxes …
=> Fix issue when changing symmetry plane of a wing in CPACS Creator

ChangeLog.md, TIGLCreator/src/CPACSAbstractModel.cpp, TIGLCreator/src/CPACSAbstractModel.h, TIGLCreator/src/CPACSFilterModel.cpp, TIGLCreator/src/CPACSFilterModel.h, TIGLCreator/src/CPACSTreeView.cpp, TIGLCreator/src/CPACSTreeView.h, TIGLCreator/src/CPACSTreeWidget.cpp, TIGLCreator/src/CPACSTreeWidget.h, TIGLCreator/src/CPACSTreeWidget.ui, TIGLCreator/src/ModificatorManager.cpp, TIGLCreator/src/ModificatorManager.h, TIGLCreator/src/TIGLCreatorWindow.ui, TIGLCreator/src/modificators/ElementModificatorInterface.h, TIGLCreator/src/modificators/ModificatorSectionsWidget.cpp, TIGLCreator/src/modificators/ModificatorSectionsWidget.h, TIGLCreator/src/modificators/NewConnectedElementDialog.cpp, TIGLCreator/src/modificators/NewConnectedElementDialog.h
Fix #628. 
We have two new context menus that can be activated in the CPACS Tree View: 
1. If a section is right-clicked, a context menu with the option to delete the section shows up. Upon clicking the section is deleted.
2. If the area between two sections is right-clicked, a context menu with the option to add a section shows up. Upon clicking the NewConnectedElementDialog opens up, with the "Where" and "startUid" comboboxes set appropriately. 
To assist the user, mouse hovering will show a line, if the mouse hovers over an area between two elements.
- Previously, the `CPACSTreeWidget` held a `QTreeView` to display the CPACS Tree. Now this `QTreeView` is subclassed (`CPACSTreeView`) to customize the mouse hovering behavior (drawing a white line between items, if the mouse hovers …
=> Fix #628 Context Menus in Tree View

examples/python/CMakeLists.txt, examples/python/create_space_ship.py, examples/python/data/empty.cpacs.xml
Fix #1183. The code comment is not correct IMHO. CTiglTransformation::Transform does not have an overload for CTiglPoint. I am not sure why the code comment was there, so I removed it. The code works as is.
I built the python bindings and tested it locally.
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [x] …
=> Update Python example from CPACS Creator

ChangeLog.md, TIGLCreator/src/TIGLCreatorSettings.cpp, TIGLCreator/src/TIGLCreatorWindow.cpp
Fixes #1186.
After the merge from tigl and cpacs-creator (especially merging the names), the new naming was inconsistent at some places. That results in 2 different registry entries. This PR resolves this by giving one consistent name.
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [x] does not …
=> Resolve inconsistent naming of the executable
