DLR-SC/tigl

TIGLViewer/src/TIGLAISTriangulation.cpp, TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerDocument.cpp, TIGLViewer/src/TIGLViewerInternal.h, TIGLViewer/src/TIGLViewerWidget.cpp, src/exports/CTiglExportStl.cpp, src/geometry/CTiglTriangularizer.cpp, src/wing/CCPACSWingProfileCST.cpp
I made changes to be able to compile tigl with opencascade 6.8.0. Please verify changes and merge them back to master.
=> Task occt680

TIGLViewer/src/ISession_Direction.cpp, TIGLViewer/src/ISession_Text.cpp, TIGLViewer/src/ISession_Text.h, TIGLViewer/src/TIGLAISTriangulation.cpp, TIGLViewer/src/TIGLAISTriangulation.h, TIGLViewer/src/TIGLViewerInternal.h, TIGLViewer/src/TIGLViewerWidget.cpp
Small modifications of TiGL Viewer to compile with the newest OpenCASCADE.
=> Port for OpenCASCADE 6.9.0 (Task #167)

appveyor.yml
This required adding QT 5.4 for VC 2010.
=> Build TiGL Viewer on AppVeyor

CMakeLists.txt, TIGLViewer/CMakeLists.txt, TIGLViewer/shaders/PhongShading.fs, TIGLViewer/shaders/PhongShading.vs, TIGLViewer/src/TIGLViewer.qrc, TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerContext.h, TIGLViewer/src/TIGLViewerWidget.cpp, TIGLViewer/src/TIGLViewerWidget.h, TIGLViewer/src/TIGLViewerWindow.cpp, TIGLViewer/src/TIGLViewerWindow.ui, TIGLViewer/src/main.cpp, cmake/FindOpenCASCADE.cmake
The reflection plot (or Zebra plot) is used to determine the quality of surfaces. It allows to check surface (dis)continuities of the C2 level.
The plot can be engaged by pressing ALT+R inside TiGL Viewer.
=> Added reflection plot in TiGLViewer

TIGLViewer/CMakeLists.txt, TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerDocument.cpp, src/fuselage/CCPACSFuselage.cpp, src/fuselage/CCPACSFuselage.h, src/fuselage/CCPACSFuselages.cpp, src/generated/UniquePtr.h, src/geometry/CTiglTransformation.cpp, src/geometry/CTiglTransformation.h, src/rotor/CCPACSRotorBladeAttachment.cpp, src/rotor/CCPACSRotorBladeAttachment.h, src/rotor/CTiglAttachedRotorBlade.cpp, src/wing/CCPACSWings.cpp
Continuation of pull request #227 after rebase
I just notices that I had two cpacs_3 branches after rebasing, so I deleted the old one, which unfortunately closed the last pull request.
=> Fix for rotorcraft regression in cpacs_3 branch (continuation from #227)

tests/TestData/external_component.xml
=> added mandatory name and transformation element to external objects test data

src/api/tigl.cpp, src/configuration/CCPACSConfiguration.cpp, src/generated/CPACSAircraftModel.cpp, src/generated/CPACSComponentSegment.cpp, src/generated/CPACSCpacs.cpp, src/generated/CPACSFuselage.cpp, src/generated/CPACSFuselageCutOut.cpp, src/generated/CPACSFuselageSegment.cpp, src/generated/CPACSGuideCurve.cpp, src/generated/CPACSHeader.cpp, src/generated/CPACSMaterials.cpp, src/generated/CPACSProfileGeometry.cpp, src/generated/CPACSProfiles.cpp, src/generated/CPACSRotorBladeAttachment.cpp, src/generated/CPACSRotorcraftModel.cpp, src/generated/CPACSSparCell.cpp, src/generated/CPACSSparCrossSection.cpp, src/generated/CPACSToolspecific.cpp, src/generated/CPACSTransformation.cpp, src/generated/CPACSVehicles.cpp, src/generated/CPACSWing.cpp, src/generated/CPACSWingComponentSegmentStructure.cpp, src/generated/CPACSWingRibCrossSection.cpp, src/generated/CPACSWingRibsDefinition.cpp, src/generated/CPACSWingSegment.cpp, src/generated/CPACSWingShell.cpp, src/system/CTiglError.cpp, src/system/CTiglError.h
=> Cpacs 3 make tigl error exception

.travis.yml
=> Added continuous integration on macOS

src/generated/CPACSCellPositioningChordwise.cpp, src/generated/CPACSCellPositioningSpanwise.cpp, src/generated/CPACSGuideCurve.cpp, src/generated/CPACSMaterial.cpp, src/generated/CPACSMaterialDefinition.cpp, src/generated/CPACSPostFailure.cpp, src/generated/CPACSProfileGeometry.cpp, src/generated/CPACSRotorBladeAttachment.cpp, src/generated/CPACSSparPosition.cpp, src/generated/CPACSWingRibsDefinition.cpp, src/generated/CPACSWingRibsPositioning.cpp, src/generated/TixiHelper.cpp
As requested at the end of PR #250, the generator has been updated to generate better formatted expressions for choice validation
=> Better formatting of choice validation expressions

bindings/java/src/de/dlr/sc/tigl3/TiglNativeInterface.java, doc/Doxyfile.in, src/api/tigl.cpp, src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/fuselage/CCPACSFuselageSegment.cpp, tests/tiglCommonFunctions.cpp
This is done by adding the API function tiglCheckPointInside.
This closes issue #262
=> Added function to check, if point is inside shape

src/fuselage/CCPACSFuselage.cpp, src/fuselage/CCPACSFuselage.h, src/fuselage/CCPACSFuselageSegment.cpp, src/fuselage/CCPACSFuselageSegment.h, tests/TestData/simpletest-halfmodel.cpacs.xml, tests/tiglFuselage.cpp
=> Ignore symmetry plane for fuselage surface area computation

appveyor.yml
=> Added java builds to appveyor

.travis.yml, CMakeLists.txt, appveyor.yml, bindings/java/CMakeLists.txt, examples/java_demo/CMakeLists.txt, examples/java_demo/build.gradle.in
The java bindings were a bit neglected recently. To avoid this in future, we are building and running the demo against the created bindings now.
=> Compile and run the java demo as another test case

src/common/typename.cpp, src/common/typename.h, src/cpacs_other/CTiglUIDManager.cpp, tests/tiglUtilities.cpp, thirdparty/boost_1_63_0/modules.txt
=> Better error messages in CTiglUIDManager

.travis.yml, CMakeLists.txt, appveyor.yml, bindings/java/src/de/dlr/sc/tigl3/TixiNativeInterface.java
This PR adjusts the CI. such that tigl is built with tixi3.
=> Make tigl3 build with tixi3

.travis.yml, TIGLViewer/src/TIGLViewerWidget.cpp, TIGLViewer/src/TIGLViewerWidget.h
TiGL Viewer: Added functions to set camera positions
The following functions where added
- setLookAtPosition(x, y, z)
- setCameraPosition(elevationAngle, azimuthAngle)
They can be used from the console to e.g. create movies.
=> Issue 315: Camera controlling functions for TiGL Viewer

src/common/CreateIfNotExists.h, src/fuselage/CCPACSFuselageSegment.cpp, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingSegment.cpp
This mainly adds missing template parameters. These issues occured on the open build service on SLED 11, RHEL 6 etc ...
=> Fixed build on old GCCs

src/cpacs_other/CTiglUIDManager.cpp, src/cpacs_other/CTiglUIDManager.h, src/fuselage/CCPACSFuselage.h, src/fuselage/CCPACSFuselageProfiles.cpp, src/fuselage/CCPACSFuselageProfiles.h, src/geometry/CTiglRelativelyPositionedComponent.cpp, src/wing/CCPACSWingSegment.cpp
* added some TIGL_EXPORTs
* formatting
* removed an unnecessary cast
* added CTiglUIDManager::SetParentComponents
* added CCPACSFuselageProfiles::AddFuselageProfile override
* removed CCPACSFuselageSectionElement::GetProfileIndex
* prepared code for relative positioning in CTiglRelativelyPositionedComponent
=> Refactoring

TIGLViewer/src/ISession_Direction.h, TIGLViewer/src/TIGLQAspectWindow.cpp, TIGLViewer/src/TIGLQAspectWindow.h, TIGLViewer/src/TIGLViewerContext.cpp, TIGLViewer/src/TIGLViewerWidget.cpp, src/boolean_operations/GEOMAlgo_Splitter.cxx, src/common/tiglcommonfunctions.cpp, src/contrib/MakeLoops.hxx, src/contrib/MakePatches.hxx, src/contrib/SurfTools.hxx, src/geometry/CTiglMakeLoft.cpp, src/wing/CTiglWingBuilder.cpp, tests/unittests/guideCurvePatchesMakeLoops.cpp
=> Modifications to allow compiling with OpenCascade 7.2.0

TIGLViewer/src/ISession_Text.h, TIGLViewer/src/TIGLQAspectWindow.h
=> Adaptions to allow compiling with OCC 7.2

src/fuselage/CCPACSFuselageSectionElement.cpp, src/geometry/CCPACSACSystems.cpp, src/geometry/CCPACSACSystems.h, src/geometry/CCPACSGenericSystem.cpp, src/geometry/CCPACSGenericSystem.h, src/geometry/CCPACSGenericSystems.cpp, src/geometry/CCPACSGenericSystems.h, src/geometry/CCPACSTransformation.cpp, src/geometry/CCPACSTransformation.h, src/geometry/CTiglRelativelyPositionedComponent.cpp, src/wing/CCPACSWing.cpp, src/wing/CCPACSWingSection.cpp, src/wing/CCPACSWingSectionElement.cpp
fixes #343, depends on PR #342
=> Safer CCPACSTransformation

TIGLViewer/src/TIGLViewerDocument.cpp, src/configuration/CCPACSConfiguration.cpp, src/configuration/CCPACSConfiguration.h, src/geometry/CCPACSGenericSystem.cpp, src/geometry/CCPACSGenericSystem.h, src/geometry/CTiglRelativelyPositionedComponent.cpp, src/geometry/CTiglRelativelyPositionedComponent.h, src/rotor/CCPACSRotor.cpp, src/rotor/CCPACSRotor.h, src/wing/CCPACSWing.cpp, src/wing/CCPACSWing.h, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSparSegment.cpp, src/wing/tiglwingribhelperfunctions.cpp
fixes #345, depends on PR #342
=> Consider parent transformations on query

bindings/python_internal/configuration.i, examples/python_internal/example_visualization.py
Integrated wing structure into internal python api and adapted visualization example to show wing structure.
The commit should not affect any other code branches than the python api.
Closes #376
=> Integrated wing structure into internal python api

CMakeLists.txt, appveyor.yml, ci/conda/oce-static/fixpaths.py, ci/conda/oce-static/meta.yaml
- use conda to install dependencies
- use clcache to speed up compilation
=> Refactoring of appveyor builds

TIGLViewer/src/TIGLScriptProxy.cpp, TIGLViewer/src/TIGLScriptProxy.h, bindings/java/src/de/dlr/sc/tigl3/TiglNativeInterface.java, bindings/python_internal/exports.i, src/api/tigl.cpp, src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/exports/CTiglExportIges.cpp, tests/unittests/tiglExports.cpp
=> Added unfified api export functions tiglExportComponent and tiglExportConfiguration

src/fuselage/CCPACSFrame.cpp, src/fuselage/CCPACSFrame.h
depends on #398
* added fuselage frame geometry getter (1D and 3D)
=> Added fuselage frame geometry

src/configuration/CCPACSConfiguration.cpp, src/configuration/CCPACSConfiguration.h, src/cpacs_other/CTiglUIDManager.cpp, src/cpacs_other/CTiglUIDManager.h, src/fuselage/CCPACSFuselageProfile.cpp, src/fuselage/CCPACSFuselageProfile.h, src/logging/CTiglLogging.h, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h, src/wing/CTiglWingProfilePointList.h
=> Removed further svn tags in code

src/guide_curves/CCPACSGuideCurveAlgo.h
=> bugfix in CCPACSGuideCurveAlgo

src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineAlgorithms.h, src/geometry/CTiglBSplineApproxInterp.cpp, src/geometry/CTiglBSplineApproxInterp.h, tests/unittests/tiglBSplines.cpp
Extended the approximation and interpolation function for B-spline curves by a method for merging closed curves C2 continuously. Added also a test for this extension.
=> Spline approx continuous

bindings/python_internal/configuration.i, cpacs_gen_input/CustomTypes.txt, cpacs_gen_input/ParentPointer.txt, src/common/tiglcommonfunctions.h, src/fuselage/CCPACSFuselageStringer.cpp, src/fuselage/CCPACSSkinSegment.cpp, src/fuselage/CCPACSSkinSegment.h, src/fuselage/CTiglStringerFrameBorderedObject.cpp, src/fuselage/CTiglStringerFrameBorderedObject.h, src/generated/CPACSFuselageStructure.cpp, src/generated/CPACSSkin.cpp, src/generated/CPACSSkin.h, src/generated/CPACSSkinSegment.cpp, src/generated/CPACSSkinSegment.h, src/generated/CPACSSkinSegments.cpp, src/generated/CPACSSkinSegments.h
depends on #400
* customized CCPACSSkinSegment
* added methods to CCPACSSkinSegment which allow to check whether faces, edges or points are inside the skin segment
=> Added fuselage skin segments

src/CMakeLists.txt
=> Grouping source files as on filesystem

src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineApproxInterp.cpp, src/geometry/CTiglBSplineApproxInterp.h, src/geometry/CTiglBSplineFit.cpp, src/geometry/CTiglBSplineFit.h, src/geometry/CTiglGordonSurfaceBuilder.cpp, src/geometry/CTiglInterpolateCurveNetwork.cpp
=> Adaptions to compile with OCC 7.2.0

src/api/tigl.h, src/fuselage/CCPACSFrame.cpp, src/fuselage/CCPACSFuselage.cpp, src/fuselage/CCPACSFuselage.h, src/fuselage/CCPACSPressureBulkheadAssemblyPosition.cpp, src/fuselage/CCPACSPressureBulkheadAssemblyPosition.h, tests/unittests/TestData/fuselage_structure-v3.xml
depends on #400
* added pressure bulkhead geometry getter
=> Added fuselage pressure bulkhead

src/fuselage/CCPACSCrossBeamAssemblyPosition.cpp, src/fuselage/CCPACSCrossBeamAssemblyPosition.h, src/fuselage/CCPACSFuselage.cpp
added cross beam geometry and cut geometry getter
=> Added fuselage cross beam

src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/fuselage/CCPACSCargoCrossBeamStrutsAssembly.cpp, src/fuselage/CCPACSCrossBeamStrutAssemblyPosition.cpp, src/fuselage/CCPACSCrossBeamStrutAssemblyPosition.h
Depends on #408
added cross beam strut geometry getter
=> Added fuselage cross beam strut

src/api/tigl.h, src/fuselage/CCPACSDoorAssemblyPosition.cpp, src/fuselage/CCPACSDoorAssemblyPosition.h, src/fuselage/CCPACSFrame.cpp, src/fuselage/CCPACSFrame.h, src/fuselage/CCPACSFuselageStringer.cpp, src/fuselage/CCPACSFuselageStringer.h, src/fuselage/CTiglStringerFrameBorderedObject.cpp, src/fuselage/CTiglStringerFrameBorderedObject.h
* added geometry getter for cargo doors
* added cut geometry getter for frames
* added cut geometry getter for stringers
=> Added fuselage cargo doors

src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, src/geometry/CTiglTransformation.cpp, src/wing/CCPACSWingProfile.cpp, src/wing/CCPACSWingProfile.h, src/wing/CCPACSWingProfileCST.cpp, src/wing/CCPACSWingProfileCST.h, src/wing/CCPACSWingSegment.cpp, src/wing/CCPACSWingSegment.h, src/wing/CTiglWingProfilePointList.cpp, src/wing/CTiglWingProfilePointList.h, src/wing/ITiglWingProfileAlgo.h
* added TiglShapeModifier enum
* replaced open/closed wire getters by single getter with TiglShapeModifier
* refactored CCPACSWingSegment::MakeSurfaces()
* added transformedShape() helper
=> Refactored wing profile wire getters

bindings/java/src/de/dlr/sc/tigl/TiglNativeInterface.java, src/api/tigl.cpp, src/api/tigl.h, src/common/tiglcommonfunctions.cpp, src/common/tiglcommonfunctions.h, tests/tiglCommonFunctions.cpp
=> Backport API function tiglCheckPointInside to tigl 2

src/api/tigl.h, src/fuselage/CCPACSLongFloorBeam.cpp, src/fuselage/CCPACSLongFloorBeam.h, src/fuselage/CCPACSLongFloorBeamPosition.cpp, src/fuselage/CCPACSLongFloorBeamPosition.h, src/fuselage/CCPACSLongFloorBeamsAssembly.cpp
geometry generation for long floor beams, depends on cross beams #408
=> Added fuselage long floor beam/position

bindings/python_internal/geometry.i, src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineApproxInterp.cpp, src/geometry/CTiglGordonSurfaceBuilder.cpp, src/geometry/CTiglPointsToBSplineInterpolation.cpp, tests/unittests/testctiglbsplinealgorithms.cpp, tests/unittests/tiglBSplines.cpp
This allows for more flexibilty, e.g. we can also interpoalte linearly.
=> Replaced GeomAPI_Interpolate by own interpolation in BSpline Algorithms

src/fuselage/CCPACSCrossBeamAssemblyPosition.cpp, src/fuselage/CCPACSCrossBeamAssemblyPosition.h, src/fuselage/CCPACSCrossBeamStrutAssemblyPosition.cpp, src/fuselage/CCPACSCrossBeamStrutAssemblyPosition.h
=> Refactored CCPACSCrossBeamAssemblyPosition to use Cache

src/api/tigl.cpp, tests/unittests/tiglIntersectionCalculation.cpp
=> Remove faulty null pointer checks

src/common/Debugging.h, src/common/tiglcommonfunctions.cpp, src/fuselage/CCPACSFuselageSegment.cpp
=> Fixed tiglFuselageGetPointAngle with guide curve geometries

src/geometry/CTiglBSplineAlgorithms.cpp, tests/unittests/CMakeLists.txt, tests/unittests/testctiglbsplinealgorithms.cpp
=> Fixed wrong reparametriztation with kinks

.gitignore, TIGLViewer/CMakeLists.txt, TIGLViewer/src/ModificatorWidget.cpp, TIGLViewer/src/ModificatorWidget.h, TIGLViewer/src/TIGLViewerFuselageWidget.cpp, TIGLViewer/src/TIGLViewerFuselageWidget.h, TIGLViewer/src/TIGLViewerPositioningsWidget.cpp, TIGLViewer/src/TIGLViewerPositioningsWidget.h, TIGLViewer/src/TIGLViewerTransformationWidget.cpp, TIGLViewer/src/TIGLViewerTransformationWidget.h, TIGLViewer/src/TIGLViewerWindow.cpp, TIGLViewer/src/TIGLViewerWindow.ui, TIGLViewer/src/TIGLViewerWingWidget.cpp, TIGLViewer/src/TIGLViewerWingWidget.h
HI, 
This branch contains the graphical elements of CPACSCreator.
The new graphical elements are added in "TIGLViewerWindow.ui".
Some new QWidget classes was created for some of these elements.      
These new graphical elements aren't attached to anything. Thus they don't behave correctly. Even to display it correctly, we need some underling function of the CPACSCreatorLib.
=> GUI Nutshell 

src/api/tigl.h, src/exports/CTiglExportIges.cpp, src/exports/CTiglExportIges.h
=> Implemented customizable IGES face names

src/wing/tigletaxsifunctions.cpp
The code made the assumption, that the spar is a straight line in component
segment coordinates. This is not true for tapered wings.
Now, we simply compute the intersection between the spar midplane line
and the rib face. This will be slower but should be more accurate.
Fixes #536
=> Fixed cell computation by using the correct geometries

src/generated/CPACSComponentSegment.h, src/generated/CPACSControlSurfaceBorderTrailingEdge.h, src/generated/CPACSCpacs.h, src/generated/CPACSRotor.h, src/generated/CPACSRotorBladeAttachment.h, src/generated/CPACSStructuralProfile.h, src/generated/CPACSTransformation.h, src/generated/CPACSWingCell.h, src/generated/CPACSWingSection.h, src/generated/CPACSWingSpar.h
Tweaked documentation generation
=> Regenerated with better text node parsing

src/CCPACSPoint.cpp, src/CCPACSPoint.h, src/CCPACSPointAbsRel.cpp, src/CCPACSPointAbsRel.h, src/geometry/CCPACSTransformation.cpp, src/geometry/CCPACSTransformation.h, src/geometry/CTiglRelativelyPositionedComponent.cpp, src/geometry/CTiglRelativelyPositionedComponent.h
=> Implemented setting of the component's transformation

src/exports/CTiglCADExporter.cpp
=> Added pylons to exports

cpacs_gen_input/CustomTypes.txt, src/configuration/CCPACSConfiguration.cpp, src/configuration/CCPACSConfiguration.h, src/engine_nacelle/CCPACSEnginePositions.cpp, src/engine_nacelle/CCPACSEnginePositions.h, src/exports/CTiglCADExporter.cpp, src/generated/CPACSAircraftModel.cpp, src/generated/CPACSAircraftModel.h, src/generated/CPACSEnginePosition.cpp, src/generated/CPACSEnginePosition.h, src/generated/CPACSEnginePositions.cpp, src/generated/CPACSEnginePositions.h, src/generated/CPACSRotorcraftModel.cpp, src/generated/CPACSRotorcraftModel.h
=> Add engine nacelle to CAD exports

src/engine_nacelle/CCPACSEnginePosition.cpp, src/engine_nacelle/CCPACSNacelleCowl.cpp, tests/unittests/TestData/CPACS_30_D250_10.xml
=> Fix crash in case of wrong or missing engine nacelle

src/fuselage/CCPACSFuselageSections.cpp, src/fuselage/CCPACSFuselageSections.h, src/wing/CCPACSWingSections.cpp, src/wing/CCPACSWingSections.h
for fuselage and wing sections
fixes #577
=> Add GetSection(const std::string& sectionUID) function

TIGLViewer/src/TIGLViewerUndoCommands.cpp, src/engine_nacelle/CCPACSNacelleCowl.cpp
I had to make two changes so I can compile with OCC 7.3.0. If CI builds with your older version of OCC or OCE, I would be happy if you could accept them.
=> Small adjustments to compile with OCC 7.3.0

src/math/CTiglProjectPointOnCurveAtAngle.cpp
=> math_BFGS call changed since OCC version 6.9.1

src/common/tiglcommonfunctions.cpp
=> make sure c_tries is defined for OpenCascade 6.9.0 and higher

tests/unittests/tiglACSystems.cpp
=> simple unit tests for generic systems

bindings/matlab/common.h
With this PR it should be possible to compile the matlab bindings for both the old and the new Matlab API.
I did not touch the code for the old API so I assume everything still works for older Matlab versions. Compilation of Matlab bindings previously failed for newer versions, which is fixed in this PR. 
I tested the *compilation* with Matlab R2019b. I did **not** test the bindings themself, however! I don't know if and where the two effected functions `nonzerocount` and `isallinteger` are used.
fixes #650
=> adapt matlab bindings to new Matlab API

src/api/tigl.cpp, src/wing/CCPACSWingComponentSegment.cpp, src/wing/CCPACSWingComponentSegment.h, tests/unittests/tiglFuselageSegment.cpp, tests/unittests/tiglWingComponentSegment.cpp
Fixes #685. Check the issue description for more details.
=> Refactor: Don't use exceptions to obtain references to geometric components

src/geometry/CTiglPatchShell.cpp, tests/unittests/testCTiglPatchShell.cpp
Minor fix to prevent a hard crash in `CTiglPatchShell`. Fixes #700
=> avoid hard crash in CTiglPatchShell

bindings/python_internal/geometry.i, src/fuselage/CCPACSFuselageProfile.cpp, src/geometry/CTiglApproxResult.h, src/geometry/CTiglBSplineAlgorithms.cpp, src/geometry/CTiglBSplineAlgorithms.h, src/geometry/CTiglBSplineApproxInterp.h, src/geometry/CTiglInterpolateCurveNetwork.cpp, tests/unittests/cpacsConfiguration.cpp, tests/unittests/testctiglbsplinealgorithms.cpp
This PR reduces the complexity of the fuselage surfaces. 
This should improve runtime performance for boolean operations with the fuselage, i.e. structure computation, general fusing etc.
To do so, the fuselage profiles are reparametrized in a way, that their knot distribution is uniform and the number of knots is a power of 2 (+1). This way, knot vectors of multiple profiles are always compatible with each other leading to much less cluttered knot vectors in the final surface.
Before this commit, we had the following sitation. Assume, we have three profiles that are created by interpolation:
```
[0, 0, 0, 0.26, 0.51, 0.77, 1., 1., 1.]
[0, 0, 0,  0.45, 1., 1., 1.]
[0, 0, 0, 0.121, 0.259, 0.379, 0.5, 0.63, 0.72, 0.87, 1., 1., 1.]
```
This results in a merged knot vector like the following: …
=> Reduce fuselage complexity

src/geometry/CTiglRelativelyPositionedComponent.cpp, src/geometry/CTiglRelativelyPositionedComponent.h
=> Removed non-optional symmetry case

src/CMakeLists.txt
=> Marked tigl3_static as a STATIC lib

doc/Doxyfile.in, doc/header.html, doc/stylesheet.css
Newer doxygen versions made some structural changes to the html code and the html was rendered not as intended.
This fixes these style issues.
Also, I changed the behaviour to enable an easier doxygen upgrade.
Closes #722
=> Fixed style for new doxygen

tests/tiglviewer-report/README.md, tests/tiglviewer-report/generate_report.py
=> Support multiple input files for tiglviewer-report

TIGLViewer/src/CommandLineParameters.h, TIGLViewer/src/TIGLViewerApp.cpp, TIGLViewer/src/TIGLViewerWindow.cpp, TIGLViewer/src/TIGLViewerWindow.h, tests/tiglviewer-report/generate_report.py
Fixes #800 
Tested manually and with the generate_report.py Python script with https://github.com/DLR-SC/tigl/blob/master/tests/unittests/TestData/CPACS_30_D250_10.xml, which will cause error dialogs to open.
=> add --suppress-errors option to TiGLViewer

src/engine_nacelle/CCPACSEnginePosition.cpp
Hotfix: Fixes a pointer to temporary issue
Detected while running the tiglviewer-report script with adress sanitizer enabled.
=> hotfix: fix pointer to temporary

TIGLViewer/src/TIGLViewerMaterials.h, TIGLViewer/src/TIGLViewerSettings.cpp, TIGLViewer/src/TIGLViewerSettings.h, TIGLViewer/src/TIGLViewerSettingsDialog.cpp, TIGLViewer/src/TIGLViewerWidget.cpp
This is required on RHEL based systems
=> Fixed build with qt4

CMakeLists.txt, bindings/python_internal/common.i, src/system/CSharedPtr.h, src/system/CheckedMutex.h, src/tigl_config.h.in
This remove old code, for pre c++11 compilers.
=> Assume having C++11 available

src/geometry/CTiglPointsToBSplineInterpolation.h
Fixes #822.
This one is hard to test programmatically, removing the reference resolved my issue. It seems to only come up in combination with the swig bindings and I assume it has something to do with how Python manages its memory internally. We should probably add some simple integration tests for our python bindings to catch stuff like this.
=> Store handle to points by value

CMakeLists.txt
=> bump minimum cmake version to 3.11

tests/integrationtests/CMakeLists.txt, tests/unittests/CMakeLists.txt
Fixes #892. The custom cmake command is invoked at the end of each build: https://stackoverflow.com/questions/34799916/copy-file-from-source-directory-to-binary-directory-using-cmake
=> Fix cmake config with TestData

src/boolean_operations/CCutShape.h
=> Add docstring

src/wing/CCPACSWingComponentSegment.h
in order to clarify the difference between WingComponentSegment and WingSegment
=> adding doctring

src/api/tigl.h, src/boolean_operations/CBooleanOperTools.h, src/wing/CCPACSWingSection.h
=> adding docstrings

TIGLViewer/src/TIGLViewerDocument.cpp, src/api/tigl.cpp, src/configuration/CCPACSConfiguration.cpp, src/configuration/CCPACSConfiguration.h
=> Fix typo (fix #992)

.github/workflows/sync-cpacscreator.yml
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| The code is properly documented with doxygen docstrings | <ul><li>- [ ] yes </li><li>- [x] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Changes are documented at the top of ChangeLog.md …
=> Add Github action to sync cpacs_creator_dev_merge with master

ChangeLog.md, TIGLViewer/src/TIGLScriptProxy.cpp, TIGLViewer/src/TIGLScriptProxy.h, src/api/tigl.cpp, src/api/tigl.h, src/cpacs_other/CTiglUIDManager.cpp, src/cpacs_other/CTiglUIDManager.h, tests/unittests/tiglTransformationBenchmark.cpp
This adds an api function that allows to transform local coordinates to global space.
This PR:
- Adds the API function
- Adds tests
- Adds the integration of the function into TiGLViewer
Note: I needed to make the function `CTiglUIDManager::GetRelativeComponent` public. I don't see any reason, why it should be private and I needed it for implementation. 
- Unit tests
- Tests in TiGL Viewer
| At least one test for the new functionality was added.  | <ul><li>- [x] yes </li><li>- [ ] does not …
=> Added the function tiglComponentTransformPointToGlobal to transform a point in local coordinate systems to the global

environment.yml
| At least one test for the new functionality was added.  | <ul><li>- [ ] yes </li><li>- [ ] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| New classes have been added to the Python interface.    | <ul><li>- [ ] yes </li><li>- [ ] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| The code is properly documented with doxygen docstrings | <ul><li>- [ ] yes </li><li>- [ ] does not apply</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Changes are documented at the top of ChangeLog.md …
=> Unpin python version
